// web/src/components/Header/header.jsx
import React from 'react'
import { Link } from 'react-router-dom'

export default props => (
    <header className='main-header'>
        <Link to='/' className='logo'>
            <span className='logo-mini'><b>Te</b>E</span>
            <span className='logo-lg'>
                <i className='fa fa-newspaper-o'></i>
                <b> Teste</b> Estadão
            </span>        
        </Link>
        <nav className='navbar navbar-static-top'>
            <Link to="#" className='sidebar-toggle' data-toggle='offcanvas'></Link>
        </nav>
    </header>
)

// resources/js/components/Header.vue
<template>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
            <router-link to="/" class="navbar-brand">Teste para o Estadão</router-link>
        </div>
    </nav>
</template>

<script>
    export default {
        name: "Header"
    }
</script>
